name: Publish to NPM

on:
  push:
    branches:
      - test/ci
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}
      - name: Publish
        run: |
          corepack enable
          pnpm install --frozen-lockfile
          git diff
          pnpm build
          git diff
          pnpm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
